### ISSUE TITLE
Text properties of underlying text reflected in popup

### ISSUE THREAD

**Issue by DarwinAwardWinner** [auto-complete/popup-el#105]
It seems that some properties of the text under a popup such as bold and italic can be applied to rows of the popup over top of those lines, as shown in the screenshot: 

![emacs-auto-complete-bug](https://cloud.githubusercontent.com/assets/228145/15480907/bda566e2-20dc-11e6-8f6e-b455cd411e68.png)

Notice the three lines with Errors in bold are also bold in the popup. This bug has also been reported in auto-complete [here](https://github.com/auto-complete/auto-complete/issues/21) and in emacs-live [here](https://github.com/overtone/emacs-live/issues/72), with a potential fix at the second link.

**Comment by DarwinAwardWinner** [comment]
This seems to be fixed by having `popup-face` inherit from the `default` face.

**Comment by syohex** [comment]
Thanks for reporting issue. I applied you suggestion. Please check latest version. And report us if you still have any issues.
