### ISSUE TITLE
Keep custom item face for isearch.

### ISSUE THREAD

**Issue by kostafey** [auto-complete/popup-el#109]
The following menu for example is created with custom `font-lock-keyword-face` foreground:
```lisp
(let ((my-custom-face `(:foreground ,(face-attribute
                                      'font-lock-keyword-face :foreground)
                        :background ,(face-attribute
                                      'popup-face :background))))
  (popup-menu* (list
                (popup-make-item "abc" :face my-custom-face)
                (popup-make-item "bcd" :face my-custom-face)
                (popup-make-item "cde" :face my-custom-face))
               :isearch t))
```
then I type "b" and items style returned to default. Is it possible to keep custom face for isearch too?

**Comment by syohex** [comment]
Sorry very too late response. Could you show us screencast or screenshots about this issue ? I suppose I cannot reproduce.

**Comment by kostafey** [comment]
Bottom "abc" style returned to default:
![output](https://cloud.githubusercontent.com/assets/1282079/22825804/40c97b84-efa0-11e6-9895-2df008dd41de.gif)

**Comment by syohex** [comment]
![popup](https://cloud.githubusercontent.com/assets/554281/22854403/38f08e68-f0b1-11e6-90a3-b1895275d5c6.gif)

I cannot reproduce as above gif. Is this your theme problem ?

**Comment by jcs090218** [comment]
@kostafey Ping! :)

**Comment by kostafey** [comment]
@jcs090218, hello! Thank you for `auto-complete` projects support!
The problem in fuzzy-matching (via `flx`) faces, which overwrite `popup-el` ones.
