### ISSUE TITLE
Release version 0.5.10?

### ISSUE THREAD

**Issue by gcv** [auto-complete/popup-el#136]
Since #135 is now merged, I'd like to update the popup.el dependency in https://github.com/gcv/julia-snail. That way, users of MELPA Stable can have improved performance, and the dependency version in Snail is correct.

Would you consider tagging and releasing version 0.5.10 of popup.el so it goes into MELPA Stable?

PS: Also, 0.5.9, though noted in the source file, does not seem to have been tagged. So MELPA Stable is stuck on 0.5.8.

Thanks!

**Comment by jcs090218** [comment]
I've released `0.5.9`. :)

I think that's the next version.
