### ISSUE TITLE
how to configure it?

### ISSUE THREAD

**Issue by wuqian-ying** [auto-complete/popup-el#137]
someone like manual configure it, how to work out it?

**Comment by jcs090218** [comment]
I'm sorry, I don't understand your request. Can you elaborate a bit further? Thanks!

**Comment by wuqian-ying** [comment]
。。。i'm sorry i want to configure it but i don't know how to configure ，抱歉，我不是很熟悉英语，我想动手的去配置他，但是我没有找到教程或者参照物

**Comment by wuqian-ying** [comment]
手动的去配置。

**Comment by jcs090218** [comment]
他是個庫, 所以基本上沒有什麼可以配置的. 你是說呼叫?

其他的配置就只有這些:

https://github.com/auto-complete/popup-el/blob/71cede0588c10526f88dd0375bce776ec2eed05e/popup.el#L912

https://github.com/auto-complete/popup-el/blob/71cede0588c10526f88dd0375bce776ec2eed05e/popup.el#L187-L206

https://github.com/auto-complete/popup-el/blob/71cede0588c10526f88dd0375bce776ec2eed05e/popup.el#L1123-L1141

到原代碼搜尋 `defcustom`, `defface` 就可以找到可以配置的變數. 希望有幫助到您!

**Comment by wuqian-ying** [comment]
蟹蟹(thanks)，他工作了（it's worked）
