### ISSUE TITLE
Line feeds can be ignored in `popup-tip`

### ISSUE THREAD

**Issue by abicky** [auto-complete/popup-el#43]
Line feeds can be ignored in `popup-tip` because `fill-region` ignores them.
Here is an example:

```
ELISP> (popup-fill-string "line 1\nline 2" 12)
(11 "line 1 line" "2")
```

I wonder if this is expected behavior.
FYI, we can avoid it by setting `use-hard-newlines` to non-nil.

```
ELISP> (defadvice fill-region (before my-fill-region activate)
         (setq use-hard-newlines t))
fill-region
ELISP> (popup-fill-string (format "line 1%sline 2" (propertize "\n" 'hard t)) 12)
(6 "line 1" "line 2")
```

**Comment by abicky** [comment]
I thought this behavior was not expected, but it seems expected, so I'll close this issue.

**Comment by jcs090218** [comment]
Glad this is resolved! I appreciated your confirmation!
