### ISSUE TITLE
popup-tip convert faces

### ISSUE THREAD

**Issue by tigermonkey** [auto-complete/popup-el#67]
Hi, I am trying to display some text with popup-tip. The text may contain italics or bold, but I want it to display with the tooltip face as the base, rather than the buffer's default.

```
(popup-tip  #("foo bar" 0 3 (face bold) 3 4 nil 4 7 (face italic)) :nostrip t)
```

Can `popup-tip` do this conversion or do I have to do the conversion myself?

**Comment by jcs090218** [comment]
Cool, I guess this issue is resolved?

Close this now! Feel free to reopen this if you find it useful.
