### ISSUE TITLE
PopUp close

### ISSUE THREAD

**Issue by guancio** [auto-complete/popup-el#7]
I'm using popup.el but I'm not able to close or open the popup help
I'm using the code

(require 'popup)
(define-key popup-menu-keymap [esc] 'popup-close)
(popup-menu\* '("hello" "word"))

But using left or esc have no effect and the popup remain opened until I select an element

**Comment by jgkamat** [comment]
I had to do:

`(define-key popup-menu-keymap [escape] 'keyboard-quit)`

The above snippet didn't work for me.
