### ISSUE TITLE
How to add image onto overlay?

### ISSUE THREAD

**Issue by zhangkaiyulw** [auto-complete/popup-el#82]
Is it possible?

Thanks.

**Comment by m2ym** [comment]
No, it's not. What kind of image do you want to put?

**Comment by jcs090218** [comment]
@zhangkaiyulw Did @m2ym answer your question? :)

Thanks!

**Comment by zhangkaiyulw** [comment]
@jcs090218 Yes, haha. It's been 5 years.

**Comment by jcs090218** [comment]
No worries! Always feel good to help! ;)
