### ISSUE TITLE
word-wrap in popup-tip

### ISSUE THREAD

**Issue by yi-tang** [auto-complete/popup-el#87]
Hi,

Is there a variable that I configure to turn on the word-wrap feature in `popup-tip` function?

**Comment by syohex** [comment]
No.

Would you tell us use case of this ?

**Comment by yi-tang** [comment]
Yeah, I found `popup-up` package is really useful to show inline documentation, but as you can see in the following picutre, 

![screenshot 2015-03-25 20 22 47](https://cloud.githubusercontent.com/assets/6054101/6834608/13e698fe-d32d-11e4-8128-8c7f60409b36.png)

the words *Britain* and *allocated* are separated into two lines, which makes the reading difficult. 

Is there a way to improve this?

**Comment by syohex** [comment]
Specify `:width` keyword parameter of `popup-tip` as bellow.

```lisp
(popup-tip "The winners of the latest GeoVation challenge - \"How can we enable people in Britain to live in better places?\" we selected on 11 March and the funding allocated to each team has been"
           :width 40)
```

![popup](https://cloud.githubusercontent.com/assets/554281/6840604/0a29e770-d3bf-11e4-88c4-183c21a1d5e4.png)

**Comment by yi-tang** [comment]
@syohex This is exactly what I am looking for. I should have looked on the function documentation, thank you very much!

**Comment by syohex** [comment]
You are welcome.
