### ISSUE TITLE
Popup fails to align correctly in Emacs Lisp mode

### ISSUE THREAD

**Issue by oracleyue** [auto-complete/popup-el#90]
It works incorrectly in elisp mode. Different lines in the function list (the left dialogue) seem have different length, so do the associated dialogue (the right one) for more details. The problem is illustrated as 
![screen shot 2015-06-08 at 16 33 08](https://cloud.githubusercontent.com/assets/5046605/8037260/07d06774-0dfd-11e5-8032-4d6d6dc62856.png)
Maybe due to the upgrade of packages one month ago. It showed correctly before. 
However, it still works well in cc-mode or python-mode, shown as
![screen shot 2015-06-08 at 16 41 04](https://cloud.githubusercontent.com/assets/5046605/8037372/b38f62cc-0dfd-11e5-80c0-26a79b6b5eae.png)

---------------------------------------------------------
One more question:
Could we stop the blank in the left dialogue due to the line wrapping in the right dialogue by adding some configurations, as shown in the above figures or the figure below in python mode? (when I use "wrap at window edge" or "word wrap"; appearing in any modes) . 
![screen shot 2015-06-08 at 16 57 45](https://cloud.githubusercontent.com/assets/5046605/8037689/a5925a42-0dff-11e5-80ff-eb8dbf423084.png)
When I use "truncate long line", it doesn't have this problem, but not satisfactory to be a solution due to the large length of most functions.
![screen shot 2015-06-08 at 16 53 06](https://cloud.githubusercontent.com/assets/5046605/8037581/daf165f8-0dfe-11e5-9812-cb8a625c8131.png)
---------------------------------------------------------

version:
emacs: 24.4.1
ac-complete: 20150408.1132
popup: 20150315.612

**Comment by syohex** [comment]
> One more question:
> Could we stop the blank in the left dialogue due to the line wrapping in the right dialogue by adding some configurations, as shown in the above figures or the figure below in python mode? (when I use "wrap at window edge" or "word wrap"; appearing in any modes) .

Adjust `ac-max-width as below.

```lisp
(setq ac-max-width 0.5)
```

**Comment by oracleyue** [comment]
@syohex  Unfortunately this doesn't work. I guess the problem does come from the width of autocomplete menu. Once I use mouse to sightly stretch the width of emacs window, the blank line due to the line wrap will disappear. However, when I insert and autocomplete again, it reappear. Thus, there is an inappropriate value for the total width of popup menu (the left + the right dialogue).  
Do you have this problem? 
For both the first and second problems I fired, do encounter them in your emacs? Many thanks!

**Comment by oracleyue** [comment]
The first problem for emacs lisp mode is strange. I never have any problems on elisp auto-completion until recently, the elisp mode is supposed to the most "perfect" one.

**Comment by oracleyue** [comment]
@syohex  The second problem is due to my configuration. When I use my "clean" type, I don't see such a problem. I will figure out what leads to this trouble. 
Regarding the first, it is also due to my configuration:
I use different "height" of font for "default" and "fixed-pitch" faces, which causes this problem. 

Sorry for firing a fake issue. Many thanks for your answer anyway!

**Comment by oracleyue** [comment]
I finally locate the source of this bug:

> the build-in *linum* 0.9.24 conflicts with auto-complete, which causes the second problem.

This is the second bug caused by linum-mode, beside it causes org-mode to be extremely slow when it contains hundreds of lines. Now I have to disable it in sh-,elisp-, python-, and cc-, etc. mode again. sigh...

Could you suggest me where to fire the bug? Should it be considered as a bug in *popup.el*? (I tend to consider it as a bug in *linum.el*, but *linum.el* seems to be an official part of emacs?)

**Comment by oracleyue** [comment]
Fine, this bug is caused by *linum-mode* together with
```
(fringe-mode '(0 . nil))
```
If without this configuration of *fringe-mode*, it works well. That's why I always feel that, with one more letter space, it would work fine.

So nothing wrong related to popup.el. cheers~
