### ISSUE TITLE
Failed to install popup-el using cask

### ISSUE THREAD

**Issue by kb01** [auto-complete/popup-el#98]
Hello,

I got an error after running make on the popup-el source code folder: 

```
Selector: t
Passed:  32
Failed:  1 (1 unexpected)
Skipped: 0
Total:   33/33

Started at:   2016-03-14 11:20:37+0000
Finished.
Finished at:  2016-03-14 11:20:38+0000

..........F......................

F popup-test-height-limit-bottom
    (ert-test-failed
     ((should
       (eq
	(popup-test-helper-popup-end-line)
	(-
	 (window-body-height)
	 1)))
      :form
      (eq 34 31)
      :value nil))
```

I'm trying to install popup-el 0.5.3 on Emacs 24.5.1.

Any help will be much appreciated.
Thank you.

**Comment by syohex** [comment]
I cannot reproduce your issue with Emacs 24.3, 24.4, 24.5, 25-pretest.

**Comment by kb01** [comment]
@syohex Thank you for your reply.
That seems little-bit strange: may I have a bug somewhere in my OS?
Anyway, what does this error suggest? Note: I'm using Arch distribution.
Thank you.

**Comment by kb01** [comment]
It worked with 25-pretest.
Thank you for pointing that out to me.
